// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvE26z3vW1C2TwFjrvcFI_fRwzBZ3xwUg',
    appId: '1:1007252695090:web:4ed53fdb70b2ab716ef42b',
    messagingSenderId: '1007252695090',
    projectId: 'instagram-clone-27fa8',
    authDomain: 'instagram-clone-27fa8.firebaseapp.com',
    storageBucket: 'instagram-clone-27fa8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGzzuz-HTNGhKym5X8Euzeag6iHMn4qEU',
    appId: '1:1007252695090:android:7004298a11e74fb86ef42b',
    messagingSenderId: '1007252695090',
    projectId: 'instagram-clone-27fa8',
    storageBucket: 'instagram-clone-27fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS5EZMauzQmz0wbRH2IevOFvH4iWUILpY',
    appId: '1:1007252695090:ios:c49f209b88dcb8666ef42b',
    messagingSenderId: '1007252695090',
    projectId: 'instagram-clone-27fa8',
    storageBucket: 'instagram-clone-27fa8.appspot.com',
    iosClientId: '1007252695090-j37cpdgjshlq706ug6g1219neqblgu27.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
